# Generated by Django 5.0 on 2024-01-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('author_pseudonym', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('bio', models.CharField(max_length=500)),
                ('profile_url', models.URLField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
